#Use the starter code to make a RPG battle game between ninjas and pirates.
#Customize the attack methods on both the Ninja and Pirate class.
#Have an instance of a ninja and pirate battle it out until one's health is depleted.
#Ninja Bonus: Use Inheritance, Class Methods, and Static Methods within your code.

from ninja import Ninja
from pirate import Pirate

michelangelo = Ninja("Michelangelo")

jack_sparrow = Pirate("Jack Sparrow")

michelangelo.punch(jack_sparrow)
jack_sparrow.show_stats()
jack_sparrow.punch(michelangelo)
michelangelo.show_stats()
michelangelo.kick(jack_sparrow)
jack_sparrow.show_stats()
michelangelo.potion()
michelangelo.show_stats()
jack_sparrow.potion()
jack_sparrow.show_stats()
michelangelo.punch(jack_sparrow)
jack_sparrow.show_stats()
jack_sparrow.punch(michelangelo)
michelangelo.show_stats()
michelangelo.kick(jack_sparrow)
jack_sparrow.show_stats()
michelangelo.potion()
michelangelo.show_stats()
jack_sparrow.potion()
jack_sparrow.show_stats()
michelangelo.punch(jack_sparrow)
jack_sparrow.show_stats()
jack_sparrow.punch(michelangelo)
michelangelo.show_stats()
michelangelo.kick(jack_sparrow)
jack_sparrow.show_stats()
michelangelo.punch(jack_sparrow)
jack_sparrow.show_stats()
jack_sparrow.punch(michelangelo)
michelangelo.show_stats()
michelangelo.kick(jack_sparrow)
jack_sparrow.show_stats()
michelangelo.potion()
michelangelo.potion()
michelangelo.potion()
michelangelo.potion()
michelangelo.potion()
michelangelo.potion()
michelangelo.show_stats()
jack_sparrow.potion()
jack_sparrow.potion()
jack_sparrow.potion()
jack_sparrow.potion()
jack_sparrow.potion()
jack_sparrow.show_stats()
michelangelo.punch(jack_sparrow)
jack_sparrow.show_stats()
jack_sparrow.punch(michelangelo)
michelangelo.show_stats()
michelangelo.kick(jack_sparrow)
jack_sparrow.show_stats()
michelangelo.potion()
michelangelo.show_stats()
jack_sparrow.potion()
jack_sparrow.show_stats()
michelangelo.punch(jack_sparrow)
jack_sparrow.show_stats()
jack_sparrow.punch(michelangelo)
michelangelo.show_stats()
michelangelo.kick(jack_sparrow)
jack_sparrow.show_stats()
michelangelo.potion()
michelangelo.show_stats()
jack_sparrow.potion()
jack_sparrow.show_stats()
michelangelo.punch(jack_sparrow)
jack_sparrow.show_stats()
jack_sparrow.punch(michelangelo)
michelangelo.show_stats()
michelangelo.kick(jack_sparrow)
jack_sparrow.show_stats()
michelangelo.punch(jack_sparrow)
jack_sparrow.show_stats()
jack_sparrow.punch(michelangelo)
michelangelo.show_stats()
michelangelo.kick(jack_sparrow)
jack_sparrow.show_stats()
michelangelo.potion()
michelangelo.potion()
michelangelo.potion()
michelangelo.potion()
michelangelo.potion()
michelangelo.potion()
michelangelo.show_stats()
jack_sparrow.potion()
jack_sparrow.potion()
jack_sparrow.potion()
jack_sparrow.potion()
jack_sparrow.potion()
jack_sparrow.show_stats()
jack_sparrow.knockout(michelangelo)
michelangelo.show_stats()
michelangelo.revive()
michelangelo.show_stats()